/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type {
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";
import type {
  TasksControllerFindAll200,
  TasksControllerFindAllParams,
} from ".././model";

export const tasksControllerFindAll = (
  params: TasksControllerFindAllParams,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TasksControllerFindAll200>> => {
  return axios.default.get(`/tasks`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getTasksControllerFindAllQueryKey = (
  params: TasksControllerFindAllParams
) => {
  return [`/tasks`, ...(params ? [params] : [])] as const;
};

export const getTasksControllerFindAllInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof tasksControllerFindAll>>>,
  TError = AxiosError<unknown>,
>(
  params: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTasksControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tasksControllerFindAll>>
  > = ({ signal }) =>
    tasksControllerFindAll(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof tasksControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TasksControllerFindAllInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerFindAll>>
>;
export type TasksControllerFindAllInfiniteQueryError = AxiosError<unknown>;

export const useTasksControllerFindAllInfinite = <
  TData = InfiniteData<Awaited<ReturnType<typeof tasksControllerFindAll>>>,
  TError = AxiosError<unknown>,
>(
  params: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTasksControllerFindAllInfiniteQueryOptions(
    params,
    options
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getTasksControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof tasksControllerFindAll>>,
  TError = AxiosError<unknown>,
>(
  params: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTasksControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tasksControllerFindAll>>
  > = ({ signal }) =>
    tasksControllerFindAll(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof tasksControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TasksControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerFindAll>>
>;
export type TasksControllerFindAllQueryError = AxiosError<unknown>;

export const useTasksControllerFindAll = <
  TData = Awaited<ReturnType<typeof tasksControllerFindAll>>,
  TError = AxiosError<unknown>,
>(
  params: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTasksControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const tasksControllerStart = (
  id: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.default.post(`/tasks/start/${id}`, undefined, options);
};

export const getTasksControllerStartMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerStart>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksControllerStart>>,
  TError,
  { id: number },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksControllerStart>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return tasksControllerStart(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksControllerStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerStart>>
>;

export type TasksControllerStartMutationError = AxiosError<void>;

export const useTasksControllerStart = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerStart>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof tasksControllerStart>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getTasksControllerStartMutationOptions(options);

  return useMutation(mutationOptions);
};
export const tasksControllerClaim = (
  id: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axios.default.patch(`/tasks/claim/${id}`, undefined, options);
};

export const getTasksControllerClaimMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerClaim>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksControllerClaim>>,
  TError,
  { id: number },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksControllerClaim>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return tasksControllerClaim(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksControllerClaimMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerClaim>>
>;

export type TasksControllerClaimMutationError = AxiosError<void>;

export const useTasksControllerClaim = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerClaim>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof tasksControllerClaim>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getTasksControllerClaimMutationOptions(options);

  return useMutation(mutationOptions);
};
