/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */

export type CreateTaskDtoCurrency =
  (typeof CreateTaskDtoCurrency)[keyof typeof CreateTaskDtoCurrency];

export const CreateTaskDtoCurrency = {
  AR: "AR",
  ENERGY: "ENERGY",
  POINT: "POINT",
  TOTAL_TAPED: "TOTAL_TAPED",
} as const;
