/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { EnergyChargesInDay } from "./energyChargesInDay";
import type { EnergyCreatedAt } from "./energyCreatedAt";
import type { EnergyFirstChargeInDay } from "./energyFirstChargeInDay";
import type { EnergyUpdatedAt } from "./energyUpdatedAt";
import type { Player } from "./player";

export interface Energy {
  amount: number;
  chargesInDay: EnergyChargesInDay;
  createdAt: EnergyCreatedAt;
  firstChargeInDay: EnergyFirstChargeInDay;
  id: number;
  player: Player;
  updatedAt: EnergyUpdatedAt;
}
