/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { Ambers } from "./ambers";
import type { Energy } from "./energy";
import type { PlayerCreatedAt } from "./playerCreatedAt";
import type { PlayerReferrals } from "./playerReferrals";
import type { PlayerUpdatedAt } from "./playerUpdatedAt";
import type { Points } from "./points";
import type { TotalTapped } from "./totalTapped";

export interface Player {
  ambers: Ambers;
  createdAt: PlayerCreatedAt;
  energy: Energy;
  id: number;
  points: Points;
  referrals: PlayerReferrals;
  totalTapped: TotalTapped;
  updatedAt: PlayerUpdatedAt;
  username: string;
}
