/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */

export interface PlayerAssetsDto {
  ambers: number;
  energy: number;
  points: number;
  totalTapped: number;
}
