/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { Player } from "./player";
import type { PointsCreatedAt } from "./pointsCreatedAt";
import type { PointsUpdatedAt } from "./pointsUpdatedAt";

export interface Points {
  amount: number;
  createdAt: PointsCreatedAt;
  id: number;
  player: Player;
  updatedAt: PointsUpdatedAt;
}
