/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { PaginatedResponse } from "./paginatedResponse";
import type { ReferralControllerGetReferrals200AllOf } from "./referralControllerGetReferrals200AllOf";

export type ReferralControllerGetReferrals200 = PaginatedResponse &
  ReferralControllerGetReferrals200AllOf;
