/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { SettingsDtoPriceRecovery } from "./settingsDtoPriceRecovery";
import type { SettingsDtoPriceTap } from "./settingsDtoPriceTap";

export type SettingsDtoPrice = {
  recovery?: SettingsDtoPriceRecovery;
  tap?: SettingsDtoPriceTap;
};
