/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { SettingsDtoLimits } from "./settingsDtoLimits";
import type { SettingsDtoPrice } from "./settingsDtoPrice";
import type { SettingsDtoReferralReward } from "./settingsDtoReferralReward";

export interface SettingsDto {
  limits: SettingsDtoLimits;
  price: SettingsDtoPrice;
  referralReward: SettingsDtoReferralReward;
}
