/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { SettingsDtoReferralRewardNormal } from "./settingsDtoReferralRewardNormal";
import type { SettingsDtoReferralRewardPremium } from "./settingsDtoReferralRewardPremium";

export type SettingsDtoReferralReward = {
  normal?: SettingsDtoReferralRewardNormal;
  premium?: SettingsDtoReferralRewardPremium;
};
