/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { SettingDtoPriceTapAr } from "./settingDtoPriceTapAr";
import type { SettingDtoPriceTapPoints } from "./settingDtoPriceTapPoints";

export type SettingDtoPriceTap = {
  ar?: SettingDtoPriceTapAr;
  points?: SettingDtoPriceTapPoints;
};
