/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { SettingsDtoPriceTapAr } from "./settingsDtoPriceTapAr";
import type { SettingsDtoPriceTapPoints } from "./settingsDtoPriceTapPoints";

export type SettingsDtoPriceTap = {
  ar?: SettingsDtoPriceTapAr;
  points?: SettingsDtoPriceTapPoints;
};
