/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { SettingDtoPriceRecovery } from "./settingDtoPriceRecovery";
import type { SettingDtoPriceTap } from "./settingDtoPriceTap";

export type SettingDtoPrice = {
  recovery?: SettingDtoPriceRecovery;
  tap?: SettingDtoPriceTap;
};
