/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { SettingsDtoPlayerLimits } from "./settingsDtoPlayerLimits";
import type { SettingsDtoReferralRewards } from "./settingsDtoReferralRewards";

export interface SettingsDto {
  fullChargePointsCostInEnergy: number;
  playerLimits: SettingsDtoPlayerLimits;
  referralRewards: SettingsDtoReferralRewards;
}
