/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { PaginatedResponse } from "./paginatedResponse";
import type { TasksController200AllOf } from "./tasksController200AllOf";

export type TasksController200 = PaginatedResponse & TasksController200AllOf;
