/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { Player } from "./player";
import type { Task } from "./task";
import type { TaskStatusCreatedAt } from "./taskStatusCreatedAt";
import type { TaskStatusStatus } from "./taskStatusStatus";
import type { TaskStatusUpdatedAt } from "./taskStatusUpdatedAt";

export interface TaskStatus {
  createdAt: TaskStatusCreatedAt;
  id: number;
  player: Player;
  status: TaskStatusStatus;
  task: Task;
  updatedAt: TaskStatusUpdatedAt;
}
