/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */

export type TaskType = (typeof TaskType)[keyof typeof TaskType];

export const TaskType = {
  INVITE_FRIENDS: "INVITE_FRIENDS",
  SOCIAL_SUBSCRIPTION: "SOCIAL_SUBSCRIPTION",
} as const;
