/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */

export type TaskStatusStatus =
  (typeof TaskStatusStatus)[keyof typeof TaskStatusStatus];

export const TaskStatusStatus = {
  FINISHED: "FINISHED",
  READY_FOR_CLAIM: "READY_FOR_CLAIM",
} as const;
