/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { PaginatedResponse } from "./paginatedResponse";
import type { TasksControllerFindAll200AllOf } from "./tasksControllerFindAll200AllOf";

export type TasksControllerFindAll200 = PaginatedResponse &
  TasksControllerFindAll200AllOf;
