/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { TaskDtoStatus } from "./taskDtoStatus";
import type { TaskDtoType } from "./taskDtoType";

export interface TaskDto {
  id: string;
  rewardInAmbers: number;
  status: TaskDtoStatus;
  title: string;
  type: TaskDtoType;
}
