/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { TaskDto } from "./taskDto";

export type TasksControllerFindAll200AllOf = {
  data?: TaskDto[];
};
