/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { Player } from "./player";
import type { TotalTappedCreatedAt } from "./totalTappedCreatedAt";
import type { TotalTappedUpdatedAt } from "./totalTappedUpdatedAt";

export interface TotalTapped {
  amount: number;
  createdAt: TotalTappedCreatedAt;
  id: number;
  player: Player;
  updatedAt: TotalTappedUpdatedAt;
}
