/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */

export type UpdateTaskDtoCurrency =
  (typeof UpdateTaskDtoCurrency)[keyof typeof UpdateTaskDtoCurrency];

export const UpdateTaskDtoCurrency = {
  AR: "AR",
  ENERGY: "ENERGY",
  POINT: "POINT",
  TOTAL_TAPED: "TOTAL_TAPED",
} as const;
