/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateTaskDtoCurrency } from "./updateTaskDtoCurrency";

export interface UpdateTaskDto {
  currency?: UpdateTaskDtoCurrency;
  reward?: number;
  title?: string;
}
