/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type {
  InfiniteData,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";
import type { SettingsDto } from ".././model";

export const settingsControllerFindOne = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SettingsDto>> => {
  return axios.default.get(`/settings`, options);
};

export const getSettingsControllerFindOneQueryKey = () => {
  return [`/settings`] as const;
};

export const getSettingsControllerFindOneInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof settingsControllerFindOne>>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof settingsControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSettingsControllerFindOneQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof settingsControllerFindOne>>
  > = ({ signal }) => settingsControllerFindOne({ signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof settingsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SettingsControllerFindOneInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingsControllerFindOne>>
>;
export type SettingsControllerFindOneInfiniteQueryError = AxiosError<unknown>;

export const useSettingsControllerFindOneInfinite = <
  TData = InfiniteData<Awaited<ReturnType<typeof settingsControllerFindOne>>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof settingsControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getSettingsControllerFindOneInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getSettingsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof settingsControllerFindOne>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof settingsControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSettingsControllerFindOneQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof settingsControllerFindOne>>
  > = ({ signal }) => settingsControllerFindOne({ signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof settingsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SettingsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingsControllerFindOne>>
>;
export type SettingsControllerFindOneQueryError = AxiosError<unknown>;

export const useSettingsControllerFindOne = <
  TData = Awaited<ReturnType<typeof settingsControllerFindOne>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof settingsControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSettingsControllerFindOneQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
