/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Ambeaver API
 * OpenAPI spec version: 0.0.1
 */
import type {
  InfiniteData,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";
import type { SettingDto } from ".././model";

export const settingControllerFindOne = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SettingDto>> => {
  return axios.default.get(`/setting`, options);
};

export const getSettingControllerFindOneQueryKey = () => {
  return [`/setting`] as const;
};

export const getSettingControllerFindOneInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof settingControllerFindOne>>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof settingControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSettingControllerFindOneQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof settingControllerFindOne>>
  > = ({ signal }) => settingControllerFindOne({ signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof settingControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SettingControllerFindOneInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingControllerFindOne>>
>;
export type SettingControllerFindOneInfiniteQueryError = AxiosError<unknown>;

export const useSettingControllerFindOneInfinite = <
  TData = InfiniteData<Awaited<ReturnType<typeof settingControllerFindOne>>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof settingControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSettingControllerFindOneInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getSettingControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof settingControllerFindOne>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof settingControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSettingControllerFindOneQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof settingControllerFindOne>>
  > = ({ signal }) => settingControllerFindOne({ signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof settingControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SettingControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingControllerFindOne>>
>;
export type SettingControllerFindOneQueryError = AxiosError<unknown>;

export const useSettingControllerFindOne = <
  TData = Awaited<ReturnType<typeof settingControllerFindOne>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof settingControllerFindOne>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSettingControllerFindOneQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
